### ISSUE TITLE
Cannot fetch gitlab project

### ISSUE THREAD

**Issue by Morgul** [loreanvictor/tmplr#28]
Attempting to use `tmplr` on my gitlab project doesn't work, it simply says `Working` and spins forever. Using `local` to the checked out project works perfectly, as does `tmplr preview`.

I believe this is related to issues `degit` has with gitlab and projects in subgroups; I had to switch to using `tiged` instead (mainly because of this [issue](https://github.com/tiged/tiged/pull/24)). (I found `tmplr` from a `tiged` issue, actually, and it's exactly what I want, love it so far!)

My project is here: https://gitlab.com/skewed-aspect/seed-projects/vue3-bootstrap (currently, the tmplr implementation is in the `template` branch, but `tmplr` failed on the base project).

I've tried the following commands, and they all hang:

```bash
$ npx tmplr https://gitlab.com/skewed-aspect/seed-projects/vue3-bootstrap#template
$ npx tmplr https://gitlab.com/skewed-aspect/seed-projects/vue3-bootstrap
```

Screenshot:
![image](https://github.com/loreanvictor/tmplr/assets/770655/51a33bf7-f7b8-4d93-acbf-30ec12326749)

**Comment by loreanvictor** [comment]
perhaps we should try switching to tiged instead of degit. I will take a look at this issue and the potential solution when I get the time, but if you are interested I would also very much appreciate a PR! in case you would like to try switching degit with tiged, you would need to change [this library](https://github.com/loreanvictor/tmplr-node/tree/main), specifically [this line](https://github.com/loreanvictor/tmplr-node/blob/e475432b631fda14c7ce660156a869e1c8f32c1c/src/filesystem/node-fs.ts#L2) (though tiged doesn't seem to be typed or have a typedef package, so perhaps you'd need to also add a module augmentation for that, which could be easily done by copying the [DefinitelyTyped repo](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/d8ee33e0e9951608cf26d9e1323bea0e69a1b083/types/degit)).

**Comment by Morgul** [comment]
I'll see if I can't take a look this weekend, or next week. I should have some spare time.

**Comment by loreanvictor** [comment]
ok I don't know why this issue was closed since support for subgroups wasn't still added to tmplr. in any case, [support for it is now added](https://github.com/loreanvictor/tmplr/commit/c091010d955e9d182956d85b4d4731ee481efa9b) in version 0.3.3. thanks to @Morgul for your efforts.
